{"name": "test_create_courier_with_existing_login", "status": "failed", "statusDetails": {"message": "AssertionError: Сообщение об ошибке не совпадает\nassert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <test_scooter_api.TestCourierAPI object at 0x105d781a0>\n\n    @allure.feature(\"Создание курьера\")\n    @allure.story(\n        \"5. Если создать пользователя с логином, который уже есть, возвращается ошибка.\"\n    )\n    @allure.description(\n        \"Проверка, что создание пользователя с существующим логином вызывает ошибку 409 \"\n        \"с сообщением 'Этот логин уже используется'\"\n    )\n    @allure.step(\n        \"Отправляем POST-запрос на создание курьера с генирированными данными в Json файле, но с логином, который уже есть\"\n    )\n    def test_create_courier_with_existing_login(self):\n        # Генерируем новый пароль и имя, но используем старый логин\n        new_data = generate_random_courier_data()\n        new_data[\"login\"] = self.courier_data[\"login\"]  # Используем старый логин\n    \n        response = requests.post(f\"{Url.BASE_URL}/courier\", json=new_data)\n        print(\n            f\"Статус после попытки создания курьера с существующим логином: {response.status_code}\"\n        )\n    \n        assert (\n            response.status_code == 409\n        ), \"Код ответа не 409 для логина, который уже используется\"\n>       assert (\n            response.json().get(\"message\") == \"Этот логин уже используется\"\n        ), \"Сообщение об ошибке не совпадает\"\nE       AssertionError: Сообщение об ошибке не совпадает\nE       assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE         \nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.\n\nAPI-tests/test_scooter_api.py:163: AssertionError"}, "description": "Проверка, что создание пользователя с существующим логином вызывает ошибку 409 с сообщением 'Этот логин уже используется'", "steps": [{"name": "Отправляем POST-запрос на создание курьера с генирированными данными в Json файле, но с логином, который уже есть", "status": "failed", "statusDetails": {"message": "AssertionError: Сообщение об ошибке не совпадает\nassert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.\n", "trace": "  File \"/Users/vladvihrov/PycharmProjects/YAProjectSprint_7/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/vladvihrov/PycharmProjects/YAProjectSprint_7/API-tests/test_scooter_api.py\", line 163, in test_create_courier_with_existing_login\n    assert (\n"}, "start": 1725214448705, "stop": 1725214449118}], "attachments": [{"name": "stdout", "source": "91120cae-211f-45fa-bbf1-019ed235f93b-attachment.txt", "type": "text/plain"}], "start": 1725214448705, "stop": 1725214449119, "uuid": "d33894ad-bf64-4ad7-b415-b17dabb11e0d", "historyId": "c0d0d89809bbf9569925f392ada7b6a6", "testCaseId": "c0d0d89809bbf9569925f392ada7b6a6", "fullName": "API-tests.test_scooter_api.TestCourierAPI#test_create_courier_with_existing_login", "labels": [{"name": "feature", "value": "Создание курьера"}, {"name": "story", "value": "5. Если создать пользователя с логином, который уже есть, возвращается ошибка."}, {"name": "parentSuite", "value": "API-tests"}, {"name": "suite", "value": "test_scooter_api"}, {"name": "subSuite", "value": "TestCourierAPI"}, {"name": "host", "value": "MacBook-Pro-Vlad.local"}, {"name": "thread", "value": "18149-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "API-tests.test_scooter_api"}]}